spring.profiles.active=mysql
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.file-size-threshold=1KB
server.port=9000
server.http.enabled=true
server.ssl.enabled=false

logging.level.org.springframework.security=DEBUG
jwt.secret=o^^cq#n**txtcxrt#f%rtff
jwt.expirationMs=8000000

# Swagger/OpenAPI configurations
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.syntaxHighlight.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
